PPW/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import data


urlpatterns = [
    path('admin/', admin.site.urls),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('data/', data, name='data'),
    path('story9/', include('story9.urls')),
    path('', include('story1.urls')),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name="logout"),
    path('', views.story9, name='story9'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

from .models import *
from .forms import CreateUserForm

def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            request.session['username'] = request.user.username
            return redirect('story1:index')
        else:
            messages.info(request, 'Username OR password is incorrect')

    response = {}
    return render(request, 'story9/login.html', response)

@login_required(login_url='story9:login')
def logoutUser(request):
    logout(request)
    return redirect('/')

def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)

            return redirect('story9:login')

    response = {'form':form}
    return render(request, 'story9/register.html', response)

def story9(request):
    response = {}
    return render(request, 'story1/index.html', response)

story9/templates/story9/login.html
{% extends "story3/navbar.html" %}
{% load static %}
{% block content %}

<div class="container containerA h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-user-circle"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Username... " class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-unlock"></i></span>
                        </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                    </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                             <input class="btn login_btn" type="submit" value="Login">
                           </div>
                </form>

            </div>

            {% for message in messages %}
                <p id="messages">{{message}}</p>
            {% endfor %}
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'story9:register' %}" class="ml-2">Sign Up</a>
                </div>
        
            </div>
        </div>
    </div>
</div>

{% endblock content %}

story9/templates/story9/register.html
{% extends "story3/navbar.html" %}
{% load static %}
{% block content %}

<div class="container containerA h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group aa mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text" ><i class="fa fa-user-circle"></i></span>
                        </div>
                        {{form.username}}
                    </div>
                    <div class="input-group aa mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                        </div>
                        {{form.email}}
                    </div>
                    <div class="input-group aa mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-unlock"></i></span>
                        </div>
                        {{form.password1}}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-unlock"></i></span>
                        </div>
                        {{form.password2}}
                    </div>

                       <div class="d-flex justify-content-center mt-3 login_container">
                         <input class="btn login_btn" type="submit" value="Register Account">
                       </div>
                </form>
            </div>

            {{form.errors}}
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'story9:login' %}" class="ml-2">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

//Query All input fields
var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Username..';
form_fields[2].placeholder='Email..';
form_fields[3].placeholder='Enter password...';
form_fields[4].placeholder='Re-enter Password...';


for (var field in form_fields){	
form_fields[field].className += ' form-control'
}
</script>



{% endblock content %}