PPW/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import data


urlpatterns = [
    path('admin/', admin.site.urls),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('data/', data, name='data'),
    path('story9/', include('story9.urls')),
    path('', include('story1.urls')),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('delete/<int:id>', views.delete_matkul, name='delete_matkul'),
    path('story5/', views.table, name='table'),
    path('', views.create, name='create')
]

story5/models.py
from django.db import models

# Create your models here.

class Story5Model(models.Model):
    nama_matkul = models.CharField(max_length = 30)
    waktu = models.CharField(max_length=30)
    ruangan = models.CharField(max_length=30)

    def __str__(self):
        return "{}.{}".format(self.id, self.nama_matkul)

story5/forms.py
from django import forms
from .models import Story5Model
from django.forms import ModelForm

class Story5ModelForm(forms.ModelForm):
    class Meta :
        model = Story5Model
        fields = [
            'nama_matkul',
            'waktu',
            'ruangan',    
        ]

        widgets = {
            'nama_matkul':forms.TextInput(attrs={'class':'form-control','placeholder':'Masukan nama mata kuliah'}),
            'waktu':forms.TextInput(attrs={'class':'form-control','placeholder':'Masukan waktu kuliah'}),
            'ruangan':forms.TextInput(attrs={'class':'form-control','placeholder':'Masukan nama ruangan'}),
        }

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import Story5ModelForm
from .models import Story5Model
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='story9:login')
def create(request):
    form = Story5ModelForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
        return redirect('story5:table')
    context = {
        'form' : form
    }
    return render(request, 'story5/create.html',context)

@login_required(login_url='story9:login')
def table(request):
    # if request.method == "POST":
    #     Story5Model.objects.create(nama_matkul = request.POST["nama_matkul "], waktu = request.POST["waktu "], ruangan = request.POST["ruangan"])
    daftar_form = Story5Model.objects.all()

    context = {
        'daftar_form' : daftar_form
    }

    return render(request, 'story5/table.html', context)


@login_required(login_url='story9:login')
def delete_matkul(request, id):
    Story5Model.objects.filter(pk=id).delete()
    return redirect('story5:table')

story5/templates/story5/create.html
{% extends "story3/navbar.html" %}

{% block content %}
    <div class="container form" id="form">
        <h1 class="text-center">Form pendaftaran</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{form.nama_matkul.label_tag}}
            {{form.nama_matkul}}
        </div>
        <div class="form-group">
            {{form.waktu.label_tag}}
            {{form.waktu}}
        </div>
        <div class="form-group">
            {{form.ruangan.label_tag}}
            {{form.ruangan}}
        </div>
        <button type="Submit">Submit</button>
    </form>
    </div>

{% endblock content %}

story5/templates/story5/table.html
{% extends "story3/navbar.html" %}
{% block content %}

    <div class="container form">
        <h1 class="text-center">Daftar jadwal kuliah</h1>
        <table class="table mt-5">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Matkul</th>
                <th scope="col">Waktu</th>
                <th scope="col">Ruangan</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
        
                {% for post in daftar_form %}

                <tr>
                    <th scoper="row">{{forloop.counter}}</th>
                    <td>{{post.nama_matkul}}</td>
                    <td>{{post.waktu}}</td>
                    <td>{{post.ruangan}}</td>
                    <td><a class="btn btn-danger" href="{% url 'story5:delete_matkul'  id=post.id %}">Delete</a>
                </tr>

                {% endfor %}

            </tbody>
        </table>
        <a class="btn btn-primary" href="{% url 'story5:create' %}" >Add</a>
    </div>
{% endblock content %}