PPW/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import data


urlpatterns = [
    path('admin/', admin.site.urls),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('data/', data, name='data'),
    path('story9/', include('story9.urls')),
    path('', include('story1.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
    path('cv/', views.cv, name='cv'),
    path('index/', views.index, name='index')
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('delete/<int:id>', views.delete_matkul, name='delete_matkul'),
    path('story5/', views.table, name='table'),
    path('', views.create, name='create')
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('post_kegiatan', views.post_kegiatan, name='post_kegiatan'),
    path('post_peserta/<int:id_kegiatan>', views.post_peserta, name='post_peserta'),
    path('', views.activity, name='activity'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7, name='story7'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8, name='story8'),
]

story1/models.py
from django.db import models

# Create your models here.

story1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request, 'story1/index.html')

def cv(request):
    return render(request, 'story1/cv.html')

story1/templates/story1/cv.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curriculum Vitae</title>
</head>
<body>
    <fieldset>
        <legend>Curriculum Vitae</legend>
        <embed src="{% static 'story1/Kornelius_tarigan.pdf' %}" type="application/pdf" width="100%" height="700" ></embed>
    </fieldset>
</body>
</html>

story1/templates/story1/index.html
{% extends "story1/navbar.html" %}
{% load static %}
{% block content%}
    <main>
      <div class="jumbotron">
        <div class="container">
          <div class="buttonProject">
            <a class="buttoncv" href="/cv" role="button" target="blank">Visit my Curriculum Vitae</a>
            <p>Get the latest project info!</p>
            <a class="btn btn-primary btn-lg" href="/story3" role="button" target="blank">Click here</a>
          </div>
        </div>
      </div>
      <div id="about">
        <h1 class="text-center">About me</h1>
          <div class="container mr-4">
            <div class="card mb-3 " style="max-width: 700px;">
              <div class="row no-gutters">
                <div class="col-md-4">
                  <img src="{% static 'story1/IDfoto.png' %}" class="card-img img1" alt="kornelius">
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"><u>Description</u></h5>
                    <p class="card-text">Hi! I'm 19 years old, a student of Universitas Indonesia, majors Information System. My hobbies are playing music and sports.</p>
                    <p>Academic:</p>
                    <pre class="card-text"><small class="text-muted">Universitas Indonesia | 2019-present
SMAN 1 Tigabinanga | 2016-2019
                    </small></pre>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
      <div id="portfolio">
        <h1 class="text-center">Portfolio</h1>
        <div class="container">
          <div class="row">
            <div class="col-md-3">
              <div class="card">
                <img src="{% static 'story1/6.png' %}" class="card-img-top" alt="akanda">
                <div class="card-body">
                  <h5 class="card-title text-center"><small class="text-muted">Volunteer</small></h5>
                  <p class="card-text text-center">Front-end Web & Creative Design</p>
                  <a href="https://www.instagram.com/akanda.id/ " class="btn btn-primary ml-3" target="blank">Click here</a>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="card">
                <img src="{% static 'story1/podcast.png' %}" class="card-img-top" alt="podcast">
                <div class="card-body">
                  <h5 class="card-title text-center"><small class="text-muted">Winner</small></h5>
                  <p class="card-text text-center">Lomba Podcast Kominfo</p>
                  <a href="/story3" class="btn btn-primary ml-3" target="blank">Click here</a>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="card">
                <img src="{% static 'story1/comming soon.png' %}" class="card-img-top" alt="akanda">
                <div class="card-body">
                  <h5 class="card-title"></h5>
                  <p class="card-text"></p>
                  <a href="#" class="btn btn-primary ml-3">Click here</a>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="card">
                <img src="{% static 'story1/comming soon.png' %}" class="card-img-top" alt="akanda">
                <div class="card-body">
                  <h5 class="card-title"></h5>
                  <p class="card-text"></p>
                  <a href="#" class="btn btn-primary ml-3">Click here</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="contact">
        <h1 class="text-center">Contact</h1>
        <div class="container">
          <div class="row justify-content-md-center">
            <div class="col col-lg-2 text-right">
              <a href="https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox?compose=GTvVlcSKjRVjWMZPrRFJhdmQXWLDxLLLzzJtNNkqQrcpCSZNtnFVzTVRWldhXctdBvGKfKJJtPPdF" target="blank"><img src="{% static 'story1/5.5.png' %}" class="sosmed img" alt="WebKornel"></a> <br>
              <a href="https://linkedin.com/in/kornelius-tarigan-7369611a3" target="blank"><img src="{% static 'story1/4.4.png' %}" class="sosmed img" alt="WebKornel"></a> <br>
              <a href="https://www.instagram.com/korneliustarigan_/" target="blank"><img src="{% static 'story1/1.1.png' %}" class="sosmed img" alt="WebKornel"></a>
            </div>
            <div class="col-md mr-auto text-left p-2">
              <p>kornelius.sibero@gmail.com</p>
              <p>linkedin.com/in/kornelius-tarigan-7369611a3</p>
              <p>korneliustarigan_</p>
            </div>
          </div>
          </div>
      </div>
    </main>
{% endblock%}

story1/templates/story1/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

     <link rel="stylesheet" href="{% static 'story1/style.css' %}">

    <title>WebKornel</title>
    <link rel = "icon" href = "{% static 'story1/WebKornelIcon.png' %}"> 
</head>
<body>
    <header id="home">
        <div>
          <nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
              <div class="container">
                  <a class="navbar-brand" href="/index"><img src="{% static 'story1/WebKornel1.png' %}" alt="WebKornel" class="profilimg"></a>
                  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon">menu</span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav ml-auto">
                      <li class="nav-item">
                      <a class="nav-link js-scroll-trigger" href="#home">Home</a>
                      </li>
                      <li class="nav-item">
                      <a class="nav-link js-scroll-trigger" href="#about">About me</a>
                      </li>
                      <li class="nav-item">
                      <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
                      </li>
                      <li class="nav-item">
                      <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Fitur</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'story5:create' %}" target="blank">Daftar Jadwal</a>
                          <a class="dropdown-item" href="{% url 'story6:activity' %}" target="blank">Daftar Aktivitas</a>
                          <a class="dropdown-item" href="{% url 'story7:story7' %}" target="blank">Cek Accordion</a>
                          <a class="dropdown-item" href="{% url 'story8:story8' %}" target="blank">Daftar Buku</a>
                        </div>
                      </li>
                  </ul>

                  {% if user.is_authenticated %}
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="#" class="aa"><span class="glyphicon glyphicon-user"></span>Hi, {{request.user}}</a></li>
                    <li><a href="{% url 'story9:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
                  </ul>
                  {% else %}

                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'story9:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="{% url 'story9:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                  </ul>

                  {% endif %}

                  </div>
                  <!-- <span class="hello-msg">Hello, {{request.user}}</span>
                  <span ><a  class="hello-msg" href="{% url 'story1:index' %}">Logout</a></span> -->
              </div>
          </nav>
        </div>
      </header>
      {% block content%}{% endblock%}
      <footer class=" text-white p-3">
        <div class="row">
          <div class="col-md-3 text-center ml-auto p-2">
            <p>WebKornel  &copy; 2020</p>
          </div>
          <div class="col-md-3 mr-auto text-center">
            <a href="https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox?compose=GTvVlcSKjRVjWMZPrRFJhdmQXWLDxLLLzzJtNNkqQrcpCSZNtnFVzTVRWldhXctdBvGKfKJJtPPdF" target="blank"><img src="{% static 'story1/5.png' %}" class="sosmed img" alt="WebKornel"></a>
            <a href="https://linkedin.com/in/kornelius-tarigan-7369611a3" target="blank"><img src="{% static 'story1/4.png' %}" class="sosmed img" alt="WebKornel"></a>
            <a href="https://www.instagram.com/korneliustarigan_/" target="blank"><img src="{% static 'story1/1.png' %}" class="sosmed img" alt="WebKornel"></a>
          </div>
        </div>
      </footer>
  
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>